apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # These are example values - you should replace them with your actual encoded values
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 encoded "admin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  # You'll need to replace this with your actual Docker registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0ZXN0YXBwM3dvdy11eCIsInBhc3N3b3JkIjoiWU9VUl9QQVNTV09SRCIsImVtYWlsIjoiWU9VUl9FTUFJTCIsImF1dGgiOiJkR1Z6ZEdGd2NETndiM2N0ZFhnNldVOVZVbDlRUVZOVFYwOVNSQT09In19fQ==